### ISSUE TITLE
Consider moving ProposeAndReject documentation into submodule

### ISSUE THREAD

**Issue by kjetilkjeka** [olivereanderson/group_assignment#3]
https://github.com/olivereanderson/group_assignment/blob/eeb22073f56e70a440cb6a3f120fba2e5d9e121c/src/assignment/assigners/mod.rs#L11-L17

nit:

Perhaps the documentation of the propose and reject algorithm is better placed in the propose and reject module?

**Comment by olivereanderson** [comment]
I have thought about this, but the only public item in this module is the ProposeAndReject struct which I have reexported. Would you still recommend making this module public if for no other reason that moving the documentation there?

**Comment by kjetilkjeka** [comment]
No, you are right, there's not much point in having a module with only one type in it. 

Then the alternative to what you're doing is to move the documentation to the type itself.

I think both alternatives are acceptable. I would use the [`std::collections`](https://doc.rust-lang.org/std/collections/index.html) as the standard here. Put introductions and comparisons in the module documentation, and specific details in the type documentation.
