### ISSUE TITLE
Consider making functions more general by accepting slices instead of Vec

### ISSUE THREAD

**Issue by kjetilkjeka** [olivereanderson/group_assignment#4]
https://github.com/olivereanderson/group_assignment/blob/eeb22073f56e70a440cb6a3f120fba2e5d9e121c/src/assignment/assigners/mod.rs#L33-L35

https://github.com/olivereanderson/group_assignment/blob/eeb22073f56e70a440cb6a3f120fba2e5d9e121c/src/assignment/assigners/mod.rs#L39-L41

Any reason these methods cannot work on slices? All Vecs will coerce (without cost) to slices, but many slices needs allocating when converting to Vec. Accepting slices when Vec funtionality is not needed will make the code strictly more general without introducing any cost.

**Comment by olivereanderson** [comment]
I have changed this now.
