### ISSUE TITLE
Consider improving documentation of the "id property" of subjects and groups

### ISSUE THREAD

**Issue by kjetilkjeka** [olivereanderson/group_assignment#6]
https://github.com/olivereanderson/group_assignment/blob/fc3736580fd732594c76c9051dd71b2620c5ee1a/src/subjects/mod.rs#L9-L10

https://github.com/olivereanderson/group_assignment/blob/fc3736580fd732594c76c9051dd71b2620c5ee1a/src/groups/mod.rs#L6-L7

When reading the documentation I feel there's a lot of unanswered questions about the IDs.

First and foremost, what is the purpose of these IDs? How do they help me as a user of the library? I assume since they're exposed to the user of the library they're not merely an implementation detail. If they do not give the user any value, from what necessity are they exposed to the user?

Secondly, what is my responsibility when implementing these traits (related to these mentioned IDs)?
 - Are there any differences between subject ids and group ids? Do they exists in the same "id-space" or different "id-spaces"?
 - Can I make all groups and subject ids 0 if I want to? Or are any uniqueness property required?
 - What happens if I Clone the Subject/Group so there exists several totally equivalent subjects/groups?
 - What happens if I assign the same id to otherwise different subjects/groups?

**Comment by olivereanderson** [comment]
You are making some very good points. I will definitely improve the documentation for the id functions.
