### ISSUE TITLE
Consider providing simpler entry (less boilerplate) when using this library

### ISSUE THREAD

**Issue by kjetilkjeka** [olivereanderson/group_assignment#7]
To use this library I am required to define at least two types and implement the Subject and Group traits on them. It is convenient that I can implement these traits on my own types. But I feel it is too much boilerplate required if I want to do something really simple.

I feel the test_util module where you define these types used in the tests is a proof of this. You don't want to define these simple types just for writing tests. Doesn't that mean the users of the library don't want to define these simple types just for doing some easy assignments?

I feel the best alternative is to provide MVP default types for Group and Subject. You can of course also look into proc macros for  making it easier to define the group and subject types.

**Comment by olivereanderson** [comment]
I guess having a basic type implementing subject that has a name and an email field could be useful for several real world examples. Maybe also a group with a description field could make sense. What should we name these type though?

**Comment by olivereanderson** [comment]
Solved in https://github.com/olivereanderson/group_assignment/commit/1ca716d83bfea3f6ccb80da06af7e45f27eeca4c.
